apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp  
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
     containers:
     - name: nodeapp
       image: prince1996/nodeapp:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 5000
