apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp  
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
     containers:
     - name: nodeapp
       image: prince1996/nodeapp:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: nodeapp
